import type { DemoCategory, DemoItem } from "@/types/demos";

export const SEED_CATEGORIES: DemoCategory[] = [
  // Top-Level Folders
  {
    id: "11111111-1111-1111-1111-111111111111",
    name: "WordPress Websites",
    slug: "wordpress-websites",
    description: "High-conversion, scalable WordPress solutions built with modern performance standards.",
    parent_id: null,
    icon: "wordpress",
    display_order: 1,
    published: true,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    name: "Custom Websites",
    slug: "custom-websites",
    description: "Bespoke React, Next.js, and TypeScript web applications engineered for speed and scale.",
    parent_id: null,
    icon: "code",
    display_order: 2,
    published: true,
    created_at: "2026-01-01T00:00:00Z",
  },

  // WordPress Subcategories
  {
    id: "a1111111-1111-1111-1111-111111111111",
    name: "Food & Restaurant",
    slug: "food-restaurant",
    description: "Fine dining, artisan cafes, and delivery restaurants.",
    parent_id: "11111111-1111-1111-1111-111111111111",
    icon: "utensils",
    display_order: 1,
    published: true,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "a2222222-2222-2222-2222-222222222222",
    name: "E-commerce",
    slug: "ecommerce-wp",
    description: "WooCommerce storefronts with optimized checkout funnels.",
    parent_id: "11111111-1111-1111-1111-111111111111",
    icon: "shopping-bag",
    display_order: 2,
    published: true,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "a3333333-3333-3333-3333-333333333333",
    name: "Corporate & Business",
    slug: "corporate-wp",
    description: "Professional corporate, legal, and financial consulting sites.",
    parent_id: "11111111-1111-1111-1111-111111111111",
    icon: "briefcase",
    display_order: 3,
    published: true,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "a4444444-4444-4444-4444-444444444444",
    name: "Real Estate",
    slug: "real-estate-wp",
    description: "Property showcases with interactive search and listings.",
    parent_id: "11111111-1111-1111-1111-111111111111",
    icon: "building",
    display_order: 4,
    published: true,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "a5555555-5555-5555-5555-555555555555",
    name: "Agency & Creative",
    slug: "agency-creative-wp",
    description: "Creative design agencies, branding studios, and dynamic portfolio showcases.",
    parent_id: "11111111-1111-1111-1111-111111111111",
    icon: "sparkles",
    display_order: 5,
    published: true,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "a6666666-6666-6666-6666-666666666666",
    name: "Medical & Healthcare",
    slug: "medical-healthcare-wp",
    description: "Medical clinic, hospital, doctor appointment booking, and healthcare practices.",
    parent_id: "11111111-1111-1111-1111-111111111111",
    icon: "activity",
    display_order: 6,
    published: true,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "a7777777-7777-7777-7777-777777777777",
    name: "SaaS & Tech Solutions",
    slug: "saas-tech-wp",
    description: "Enterprise software, AI startups, cyber security, and managed IT services.",
    parent_id: "11111111-1111-1111-1111-111111111111",
    icon: "cpu",
    display_order: 7,
    published: true,
    created_at: "2026-01-01T00:00:00Z",
  },

  // Custom Websites Subcategories
  {
    id: "b1111111-1111-1111-1111-111111111111",
    name: "SaaS & Web Apps",
    slug: "saas-custom",
    description: "Modern software-as-a-service platforms and interactive tools.",
    parent_id: "22222222-2222-2222-2222-222222222222",
    icon: "cpu",
    display_order: 1,
    published: true,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "b2222222-2222-2222-2222-222222222222",
    name: "Agency & Portfolio",
    slug: "agency-custom",
    description: "Design studios, architecture showcases, and high-impact portfolios.",
    parent_id: "22222222-2222-2222-2222-222222222222",
    icon: "sparkles",
    display_order: 2,
    published: true,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "b3333333-3333-3333-3333-333333333333",
    name: "Headless E-commerce",
    slug: "ecommerce-custom",
    description: "Lightning-fast React/Next.js storefronts with Shopify or Medusa.",
    parent_id: "22222222-2222-2222-2222-222222222222",
    icon: "zap",
    display_order: 3,
    published: true,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "b4444444-4444-4444-4444-444444444444",
    name: "Landing Pages",
    slug: "landing-pages-custom",
    description: "High-conversion, sub-second landing pages built for campaign ROI.",
    parent_id: "22222222-2222-2222-2222-222222222222",
    icon: "layers",
    display_order: 4,
    published: true,
    created_at: "2026-01-01T00:00:00Z",
  },
];

export const SEED_DEMOS: DemoItem[] = [
  // WordPress / Food & Restaurant
  {
    id: "d-wp-1",
    category_id: "a1111111-1111-1111-1111-111111111111",
    title: "L'Aura Gastronomy",
    slug: "laura-gastronomy",
    description: "Michelin-star restaurant concept featuring interactive table reservations, seasonal culinary menus, and smooth visual storytelling.",
    thumbnail_url: "/hero-main.png",
    demo_url: "https://demo.techvrs.com/wp/laura",
    technology: "WordPress",
    stack: ["WordPress", "Elementor Pro", "OpenTable API", "ACF Pro"],
    featured: true,
    published: true,
    display_order: 1,
    created_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "d-wp-2",
    category_id: "a1111111-1111-1111-1111-111111111111",
    title: "Artisan Roast Cafe",
    slug: "artisan-roast-cafe",
    description: "Specialty coffee bar template with bean subscription purchasing, location finder, and wholesale inquiry funnel.",
    thumbnail_url: "/hero-bg.png",
    demo_url: "https://demo.techvrs.com/wp/artisan-roast",
    technology: "WordPress",
    stack: ["WordPress", "WooCommerce", "Tailwind", "Stripe"],
    featured: false,
    published: true,
    display_order: 2,
    created_at: "2026-02-02T00:00:00Z",
  },
  {
    id: "d-wp-3",
    category_id: "a1111111-1111-1111-1111-111111111111",
    title: "Urban Bistro & Bar",
    slug: "urban-bistro-bar",
    description: "Modern urban bistro and cocktail lounge featuring live event schedules, online ordering, and VIP table bookings.",
    thumbnail_url: "/hero-main.png",
    demo_url: "https://demo.techvrs.com/wp/urban-bistro",
    technology: "WordPress",
    stack: ["WordPress", "Gutenberg Blocks", "SevenRooms"],
    featured: false,
    published: true,
    display_order: 3,
    created_at: "2026-02-03T00:00:00Z",
  },

  // WordPress / E-commerce
  {
    id: "d-wp-4",
    category_id: "a2222222-2222-2222-2222-222222222222",
    title: "Veloce Luxury Apparel",
    slug: "veloce-luxury-apparel",
    description: "Minimalist fashion e-commerce storefront with instant live search, variant pickers, and optimized one-page checkout.",
    thumbnail_url: "/hero-main.png",
    demo_url: "https://demo.techvrs.com/wp/veloce",
    technology: "WordPress",
    stack: ["WordPress", "WooCommerce", "Redis Cache", "Cloudflare"],
    featured: true,
    published: true,
    display_order: 1,
    created_at: "2026-02-04T00:00:00Z",
  },
  {
    id: "d-wp-5",
    category_id: "a2222222-2222-2222-2222-222222222222",
    title: "Terra Organica Marketplace",
    slug: "terra-organica",
    description: "Eco-friendly goods and skincare store featuring recurring subscriptions, bundle discounts, and loyalty points.",
    thumbnail_url: "/hero-bg.png",
    demo_url: "https://demo.techvrs.com/wp/terra",
    technology: "WordPress",
    stack: ["WordPress", "WooCommerce Subscriptions", "WP Rocket"],
    featured: false,
    published: true,
    display_order: 2,
    created_at: "2026-02-05T00:00:00Z",
  },

  // WordPress / Corporate
  {
    id: "d-wp-6",
    category_id: "a3333333-3333-3333-3333-333333333333",
    title: "Vanguard Advisory Group",
    slug: "vanguard-advisory",
    description: "Executive financial advisory platform with interactive ROI calculators, client portal login, and compliance disclosures.",
    thumbnail_url: "/hero-main.png",
    demo_url: "https://demo.techvrs.com/wp/vanguard",
    technology: "WordPress",
    stack: ["WordPress", "Custom Block Theme", "Gravity Forms", "HubSpot CRM"],
    featured: false,
    published: true,
    display_order: 1,
    created_at: "2026-02-06T00:00:00Z",
  },
  {
    id: "d-wp-7",
    category_id: "a3333333-3333-3333-3333-333333333333",
    title: "Apex Legal Partners",
    slug: "apex-legal-partners",
    description: "High-end law practice portal featuring attorney profiles, practice area deep-dives, and secure consultation booking.",
    thumbnail_url: "/hero-bg.png",
    demo_url: "https://demo.techvrs.com/wp/apex-legal",
    technology: "WordPress",
    stack: ["WordPress", "ACF Pro", "Calendly Integration"],
    featured: false,
    published: true,
    display_order: 2,
    created_at: "2026-02-07T00:00:00Z",
  },

  // WordPress / Real Estate
  {
    id: "d-wp-8",
    category_id: "a4444444-4444-4444-4444-444444444444",
    title: "Sovereign Luxury Estates",
    slug: "sovereign-estates",
    description: "Luxury architectural properties showcase with high-res galleries, virtual walkthrough embeds, and private agent inquiries.",
    thumbnail_url: "/hero-main.png",
    demo_url: "https://demo.techvrs.com/wp/sovereign",
    technology: "WordPress",
    stack: ["WordPress", "Custom Post Types", "Mapbox GL", "Matterport Embed"],
    featured: true,
    published: true,
    display_order: 1,
    created_at: "2026-02-08T00:00:00Z",
  },

  // Custom / SaaS & Web Apps
  {
    id: "d-custom-1",
    category_id: "b1111111-1111-1111-1111-111111111111",
    title: "PulseOps Cloud Observability",
    slug: "pulseops-saas",
    description: "Developer-first infrastructure monitoring platform with interactive live telemetry graphs, team workspace switcher, and docs.",
    thumbnail_url: "/hero-main.png",
    demo_url: "https://demo.techvrs.com/custom/pulseops",
    technology: "Custom / Next.js",
    stack: ["Next.js 15", "TypeScript", "Tailwind CSS", "Recharts", "Supabase"],
    featured: true,
    published: true,
    display_order: 1,
    created_at: "2026-02-09T00:00:00Z",
  },
  {
    id: "d-custom-2",
    category_id: "b1111111-1111-1111-1111-111111111111",
    title: "CogniScale AI Platform",
    slug: "cogniscale-ai",
    description: "Enterprise generative AI orchestration suite with workflow node builder, API playground, and token usage analytics.",
    thumbnail_url: "/hero-bg.png",
    demo_url: "https://demo.techvrs.com/custom/cogniscale",
    technology: "Custom / React",
    stack: ["React 19", "Vite", "TanStack Router", "OpenAI API", "Tailwind"],
    featured: true,
    published: true,
    display_order: 2,
    created_at: "2026-02-10T00:00:00Z",
  },

  // Custom / Agency & Portfolio
  {
    id: "d-custom-3",
    category_id: "b2222222-2222-2222-2222-222222222222",
    title: "Monochrome Design Studio",
    slug: "monochrome-studio",
    description: "Award-winning digital creative agency portfolio with magnetic cursor interactions, smooth case study transitions, and dark aesthetic.",
    thumbnail_url: "/hero-main.png",
    demo_url: "https://demo.techvrs.com/custom/monochrome",
    technology: "Custom / Next.js",
    stack: ["Next.js", "Framer Motion", "Tailwind CSS", "Lenis Scroll"],
    featured: false,
    published: true,
    display_order: 1,
    created_at: "2026-02-11T00:00:00Z",
  },
  {
    id: "d-custom-4",
    category_id: "b2222222-2222-2222-2222-222222222222",
    title: "Atelier K Architects",
    slug: "atelier-k",
    description: "Spatial architectural studio index with project filtering by typology, fullscreen photo viewer, and monograph index.",
    thumbnail_url: "/hero-bg.png",
    demo_url: "https://demo.techvrs.com/custom/atelier-k",
    technology: "Custom / React",
    stack: ["React", "TypeScript", "Vite", "CSS Grid"],
    featured: false,
    published: true,
    display_order: 2,
    created_at: "2026-02-12T00:00:00Z",
  },

  // Custom / Headless E-commerce
  {
    id: "d-custom-5",
    category_id: "b3333333-3333-3333-3333-333333333333",
    title: "Kroma Minimal Hardware",
    slug: "kroma-hardware",
    description: "Ultra-fast headless hardware storefront with sub-200ms page transitions, instant cart mutations, and 3D product previews.",
    thumbnail_url: "/hero-main.png",
    demo_url: "https://demo.techvrs.com/custom/kroma",
    technology: "Custom / Next.js",
    stack: ["Next.js", "Medusa.js", "Tailwind", "Stripe Elements"],
    featured: true,
    published: true,
    display_order: 1,
    created_at: "2026-02-13T00:00:00Z",
  },

  // Custom / Landing Pages
  {
    id: "d-custom-6",
    category_id: "b4444444-4444-4444-4444-444444444444",
    title: "FlowState Productivity App",
    slug: "flowstate-landing",
    description: "Conversion-optimized SaaS launch page with interactive feature demo tabs, social proof marquee, and annual pricing calculator.",
    thumbnail_url: "/hero-main.png",
    demo_url: "https://demo.techvrs.com/custom/flowstate",
    technology: "Custom / React",
    stack: ["React", "Vite", "Tailwind CSS", "Lucide"],
    featured: false,
    published: true,
    display_order: 1,
    created_at: "2026-02-14T00:00:00Z",
  },

  // ─── Newly Added Live Demos ──────────────────────────────────────────
  // WordPress / SaaS & Tech Solutions
  {
    id: "d-wp-saasoft",
    category_id: "a7777777-7777-7777-7777-777777777777",
    title: "SaaSoft – Software & SaaS WordPress Theme",
    slug: "saasoft-saas-wordpress-theme",
    description: "Modern software, app launch, and SaaS startup WordPress theme with interactive pricing tiers and feature demonstration sections.",
    thumbnail_url: "/1.webp",
    demo_url: "http://saasoft.wpenginepowered.com/",
    technology: "WordPress",
    stack: ["WordPress", "Elementor Pro", "SaaS Startup", "WP Engine"],
    featured: true,
    published: true,
    display_order: 10,
    created_at: "2026-02-15T00:00:00Z",
  },
  {
    id: "d-wp-aifusionx",
    category_id: "a7777777-7777-7777-7777-777777777777",
    title: "AIFusionX – AI Agency & Tech WordPress Theme",
    slug: "aifusionx-ai-tech-agency-wp",
    description: "Next-generation artificial intelligence agency, machine learning SaaS, and futuristic tech startup WordPress theme by VamTam.",
    thumbnail_url: "/4.webp",
    demo_url: "https://themes.vamtam.com/?theme=aifusionx&n=1&storefront=envato-elements",
    technology: "WordPress",
    stack: ["WordPress", "Elementor", "VamTam", "AI Solutions"],
    featured: true,
    published: true,
    display_order: 11,
    created_at: "2026-02-16T00:00:00Z",
  },
  {
    id: "d-wp-zypho",
    category_id: "a7777777-7777-7777-7777-777777777777",
    title: "Zypho – Cyber Security & IT Solutions Elementor Template Kit",
    slug: "zypho-cyber-security-it-solutions",
    description: "Enterprise cyber security consulting, infrastructure defense, and managed IT services Elementor template kit.",
    thumbnail_url: "/1.webp",
    demo_url: "https://templatekit.kitprostudio.com/zypho/?storefront=envato-elements",
    technology: "WordPress",
    stack: ["WordPress", "Elementor", "Cyber Security", "IT Solutions"],
    featured: false,
    published: true,
    display_order: 12,
    created_at: "2026-02-17T00:00:00Z",
  },

  // WordPress / Agency & Creative
  {
    id: "d-wp-marpixel",
    category_id: "a5555555-5555-5555-5555-555555555555",
    title: "Marpixel – Marketing Agency WordPress Theme",
    slug: "marpixel-marketing-agency-wp",
    description: "High-conversion digital marketing agency, growth consultancy, and creative advertising studio WordPress theme.",
    thumbnail_url: "/2.webp",
    demo_url: "https://themexriver.com/wp/marpixel/?storefront=envato-elements",
    technology: "WordPress",
    stack: ["WordPress", "Elementor", "Marketing Agency", "Growth"],
    featured: true,
    published: true,
    display_order: 13,
    created_at: "2026-02-18T00:00:00Z",
  },
  {
    id: "d-wp-isak",
    category_id: "a5555555-5555-5555-5555-555555555555",
    title: "Isak – Personal Portfolio WordPress Theme",
    slug: "isak-personal-portfolio-wp",
    description: "Creative personal portfolio and resume WordPress theme featuring interactive canvas backgrounds and sleek light/dark aesthetics.",
    thumbnail_url: "/2.webp",
    demo_url: "https://isak.autodealwordpress.com/home-background/?mode=light",
    technology: "WordPress",
    stack: ["WordPress", "Elementor", "Interactive Canvas", "Portfolio"],
    featured: false,
    published: true,
    display_order: 14,
    created_at: "2026-02-19T00:00:00Z",
  },
  {
    id: "d-wp-clariver",
    category_id: "a5555555-5555-5555-5555-555555555555",
    title: "Clariver – Creative Digital Agency Elementor Template Kit",
    slug: "clariver-creative-agency-kit",
    description: "Creative digital agency, branding studio, and typography-rich design showcase Elementor template kit.",
    thumbnail_url: "/1.webp",
    demo_url: "https://clariver.tokotema.xyz/template-kit/home/?storefront=envato-elements",
    technology: "WordPress",
    stack: ["WordPress", "Elementor", "Digital Agency", "Creative Studio"],
    featured: false,
    published: true,
    display_order: 15,
    created_at: "2026-02-20T00:00:00Z",
  },

  // WordPress / Corporate & Business
  {
    id: "d-wp-bixoo",
    category_id: "a3333333-3333-3333-3333-333333333333",
    title: "Bixoo – Business Consulting & Corporate WordPress Theme",
    slug: "bixoo-business-consulting-corporate",
    description: "Enterprise business consulting, corporate advisory, and financial strategy WordPress theme with case study showcases.",
    thumbnail_url: "/3.webp",
    demo_url: "https://bixoowp.wowtheme7.com/?storefront=envato-elements",
    technology: "WordPress",
    stack: ["WordPress", "Elementor", "Consulting", "Corporate"],
    featured: false,
    published: true,
    display_order: 16,
    created_at: "2026-02-21T00:00:00Z",
  },
  {
    id: "d-wp-bizznep",
    category_id: "a3333333-3333-3333-3333-333333333333",
    title: "Bizznep – Business Consulting & Corporate WordPress Theme",
    slug: "bizznep-business-consulting-onepage",
    description: "Sleek single-page corporate consulting and business advisory layout with smooth navigation and lead generation.",
    thumbnail_url: "/4.webp",
    demo_url: "https://demo.bravisthemes.com/bizznep/home-1-onepage-2/",
    technology: "WordPress",
    stack: ["WordPress", "Elementor", "OnePage", "Bravisthemes"],
    featured: false,
    published: true,
    display_order: 17,
    created_at: "2026-02-22T00:00:00Z",
  },
  {
    id: "d-wp-brevon",
    category_id: "a3333333-3333-3333-3333-333333333333",
    title: "Brevon – Multipurpose Business & Agency WordPress Theme",
    slug: "brevon-multipurpose-business-agency",
    description: "Multipurpose business, agency, and creative portfolio WordPress theme with custom Elementor widgets.",
    thumbnail_url: "/1.webp",
    demo_url: "https://brevondemo.ex-coders.com/?storefront=envato-elements",
    technology: "WordPress",
    stack: ["WordPress", "WooCommerce", "Elementor", "Ex-Coders"],
    featured: false,
    published: true,
    display_order: 18,
    created_at: "2026-02-23T00:00:00Z",
  },

  // WordPress / Medical & Healthcare
  {
    id: "d-wp-md",
    category_id: "a6666666-6666-6666-6666-666666666666",
    title: "MD – Medical, Doctor & Healthcare WordPress Theme",
    slug: "md-medical-doctor-healthcare",
    description: "Modern clinic, hospital, doctor appointment booking, and healthcare facility WordPress theme with medical department schedules.",
    thumbnail_url: "/2.webp",
    demo_url: "https://md.axiomthemes.com/?storefront=envato-elements",
    technology: "WordPress",
    stack: ["WordPress", "Elementor", "Healthcare", "AxiomThemes"],
    featured: true,
    published: true,
    display_order: 19,
    created_at: "2026-02-24T00:00:00Z",
  },

  // Custom / SaaS & Web Apps
  {
    id: "d-custom-svg-mask",
    category_id: "b1111111-1111-1111-1111-111111111111",
    title: "SVG Mask Effect | Aceternity UI",
    slug: "svg-mask-effect-aceternity-ui",
    description: "A mask reveal effect, hover the cursor over a container to reveal what's underneath with SVG clipping paths and smooth physics.",
    thumbnail_url: "/3.webp",
    demo_url: "https://ui.aceternity.com/components/svg-mask-effect",
    technology: "Custom / React",
    stack: ["React", "Next.js", "Framer Motion", "Tailwind CSS"],
    featured: true,
    published: true,
    display_order: 20,
    created_at: "2026-02-25T00:00:00Z",
  },
  {
    id: "d-custom-paynext",
    category_id: "b1111111-1111-1111-1111-111111111111",
    title: "Paynext - Modern Fintech Website HTML Template",
    slug: "paynext-modern-fintech-website",
    description: "Feature-rich HTML template for fintech startups, digital banking, payment gateways, and crypto asset management.",
    thumbnail_url: "/3.webp",
    demo_url: "https://paynext-html.peterdraw.co/?storefront=envato-elements",
    technology: "Custom / HTML5",
    stack: ["HTML5", "Tailwind CSS", "Fintech", "Banking"],
    featured: true,
    published: true,
    display_order: 21,
    created_at: "2026-02-26T00:00:00Z",
  },

  // Custom / Agency & Portfolio
  {
    id: "d-custom-designpro",
    category_id: "b2222222-2222-2222-2222-222222222222",
    title: "Designpro - Productized Design Agency website template",
    slug: "designpro-productized-agency-nextjs",
    description: "Productized design subscription agency platform built with Next.js, featuring monthly recurring pricing plans and work galleries.",
    thumbnail_url: "/4.webp",
    demo_url: "https://designpro-next.vercel.app/?storefront=envato-elements",
    technology: "Custom / Next.js",
    stack: ["Next.js 14", "React", "Tailwind CSS", "Vercel"],
    featured: true,
    published: true,
    display_order: 22,
    created_at: "2026-02-27T00:00:00Z",
  },
  {
    id: "d-custom-danbury",
    category_id: "b2222222-2222-2222-2222-222222222222",
    title: "Danbury – Architecture & Interior Design HTML5 Template",
    slug: "danbury-architecture-interior-design",
    description: "Minimalist architectural studio, spatial construction, and contemporary interior design showcase template.",
    thumbnail_url: "/3.webp",
    demo_url: "https://html.tonatheme.com/2020/Danbury/?storefront=envato-elements",
    technology: "Custom / HTML5",
    stack: ["HTML5", "Bootstrap", "Architecture", "Interior Design"],
    featured: false,
    published: true,
    display_order: 23,
    created_at: "2026-02-28T00:00:00Z",
  },
  {
    id: "d-custom-modelissimo",
    category_id: "b2222222-2222-2222-2222-222222222222",
    title: "Modelissimo - Model Agency / Fashion Muse Template",
    slug: "modelissimo-model-agency-fashion",
    description: "High-fashion modeling agency, talent management, model composite cards, and fashion photography portfolio.",
    thumbnail_url: "/4.webp",
    demo_url: "https://design4dj.com/tf/modelissimo/?storefront=envato-elements",
    technology: "Custom / HTML5",
    stack: ["HTML5", "CSS3", "Fashion", "Talent Agency"],
    featured: false,
    published: true,
    display_order: 24,
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "d-custom-sepia",
    category_id: "b2222222-2222-2222-2222-222222222222",
    title: "Sepia - Photography Portfolio HTML Website Template",
    slug: "sepia-photography-portfolio-website",
    description: "Comprehensive photography portfolio and creative visual artist showcase template with responsive grid and masonry albums.",
    thumbnail_url: "/2.webp",
    demo_url: "https://demo.themetorium.net/html/sepia/?storefront=envato-elements",
    technology: "Custom / HTML5",
    stack: ["HTML5", "PhotoSwipe", "Grid Gallery", "Masonry"],
    featured: false,
    published: true,
    display_order: 25,
    created_at: "2026-03-02T00:00:00Z",
  },

  // Custom / Landing Pages
  {
    id: "d-custom-charifund",
    category_id: "b4444444-4444-4444-4444-444444444444",
    title: "Charifund | Nonprofit & Fundraising Charity NEXT JS Template",
    slug: "charifund-nonprofit-fundraising-nextjs",
    description: "Nonprofit fundraising charity and donation campaigns web application engineered with modern Next.js and responsive layouts.",
    thumbnail_url: "/1.webp",
    demo_url: "https://nextjs.charifund.wowtheme7.com/?storefront=envato-elements",
    technology: "Custom / Next.js",
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "Donations"],
    featured: false,
    published: true,
    display_order: 26,
    created_at: "2026-03-03T00:00:00Z",
  },
  {
    id: "d-custom-pubzi",
    category_id: "b4444444-4444-4444-4444-444444444444",
    title: "Pubzi - eSports and Gaming HTML Template",
    slug: "pubzi-esports-gaming-html-template",
    description: "High-octane eSports tournament portal, clan battle stats, twitch stream embeds, and gaming community HTML template.",
    thumbnail_url: "/3.webp",
    demo_url: "https://ex-coders.com/html/pubzi/index.html",
    technology: "Custom / HTML5",
    stack: ["HTML5", "CSS3", "JavaScript", "eSports"],
    featured: false,
    published: true,
    display_order: 27,
    created_at: "2026-03-04T00:00:00Z",
  },
];

