/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as PormtsRouteImport } from './routes/pormts'
import { Route as DemosRouteImport } from './routes/demos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PormtsIndexRouteImport } from './routes/pormts.index'
import { Route as PormtsSavedRouteImport } from './routes/pormts.saved'
import { Route as PormtsGuideRouteImport } from './routes/pormts.guide'
import { Route as PormtsCollectionsRouteImport } from './routes/pormts.collections'
import { Route as PormtsBuilderRouteImport } from './routes/pormts.builder'
import { Route as PormtsAboutRouteImport } from './routes/pormts.about'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDemosRouteImport } from './routes/admin/demos'
import { Route as PormtsPromptSlugRouteImport } from './routes/pormts.prompt.$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const PormtsRoute = PormtsRouteImport.update({
  id: '/pormts',
  path: '/pormts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosRoute = DemosRouteImport.update({
  id: '/demos',
  path: '/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PormtsIndexRoute = PormtsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PormtsRoute,
} as any)
const PormtsSavedRoute = PormtsSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => PormtsRoute,
} as any)
const PormtsGuideRoute = PormtsGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => PormtsRoute,
} as any)
const PormtsCollectionsRoute = PormtsCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => PormtsRoute,
} as any)
const PormtsBuilderRoute = PormtsBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => PormtsRoute,
} as any)
const PormtsAboutRoute = PormtsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PormtsRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemosRoute = AdminDemosRouteImport.update({
  id: '/admin/demos',
  path: '/admin/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const PormtsPromptSlugRoute = PormtsPromptSlugRouteImport.update({
  id: '/prompt/$slug',
  path: '/prompt/$slug',
  getParentRoute: () => PormtsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/demos': typeof DemosRoute
  '/pormts': typeof PormtsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/admin/demos': typeof AdminDemosRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/pormts/about': typeof PormtsAboutRoute
  '/pormts/builder': typeof PormtsBuilderRoute
  '/pormts/collections': typeof PormtsCollectionsRoute
  '/pormts/guide': typeof PormtsGuideRoute
  '/pormts/saved': typeof PormtsSavedRoute
  '/pormts/': typeof PormtsIndexRoute
  '/pormts/prompt/$slug': typeof PormtsPromptSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/demos': typeof DemosRoute
  '/prompts': typeof PromptsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/admin/demos': typeof AdminDemosRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/pormts/about': typeof PormtsAboutRoute
  '/pormts/builder': typeof PormtsBuilderRoute
  '/pormts/collections': typeof PormtsCollectionsRoute
  '/pormts/guide': typeof PormtsGuideRoute
  '/pormts/saved': typeof PormtsSavedRoute
  '/pormts': typeof PormtsIndexRoute
  '/pormts/prompt/$slug': typeof PormtsPromptSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/demos': typeof DemosRoute
  '/pormts': typeof PormtsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/admin/demos': typeof AdminDemosRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/pormts/about': typeof PormtsAboutRoute
  '/pormts/builder': typeof PormtsBuilderRoute
  '/pormts/collections': typeof PormtsCollectionsRoute
  '/pormts/guide': typeof PormtsGuideRoute
  '/pormts/saved': typeof PormtsSavedRoute
  '/pormts/': typeof PormtsIndexRoute
  '/pormts/prompt/$slug': typeof PormtsPromptSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/demos'
    | '/pormts'
    | '/prompts'
    | '/services'
    | '/sitemap.xml'
    | '/work'
    | '/admin/demos'
    | '/admin/login'
    | '/api/chat'
    | '/pormts/about'
    | '/pormts/builder'
    | '/pormts/collections'
    | '/pormts/guide'
    | '/pormts/saved'
    | '/pormts/'
    | '/pormts/prompt/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/demos'
    | '/prompts'
    | '/services'
    | '/sitemap.xml'
    | '/work'
    | '/admin/demos'
    | '/admin/login'
    | '/api/chat'
    | '/pormts/about'
    | '/pormts/builder'
    | '/pormts/collections'
    | '/pormts/guide'
    | '/pormts/saved'
    | '/pormts'
    | '/pormts/prompt/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/demos'
    | '/pormts'
    | '/prompts'
    | '/services'
    | '/sitemap.xml'
    | '/work'
    | '/admin/demos'
    | '/admin/login'
    | '/api/chat'
    | '/pormts/about'
    | '/pormts/builder'
    | '/pormts/collections'
    | '/pormts/guide'
    | '/pormts/saved'
    | '/pormts/'
    | '/pormts/prompt/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DemosRoute: typeof DemosRoute
  PormtsRoute: typeof PormtsRouteWithChildren
  PromptsRoute: typeof PromptsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkRoute: typeof WorkRoute
  AdminDemosRoute: typeof AdminDemosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pormts': {
      id: '/pormts'
      path: '/pormts'
      fullPath: '/pormts'
      preLoaderRoute: typeof PormtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos': {
      id: '/demos'
      path: '/demos'
      fullPath: '/demos'
      preLoaderRoute: typeof DemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pormts/': {
      id: '/pormts/'
      path: '/'
      fullPath: '/pormts/'
      preLoaderRoute: typeof PormtsIndexRouteImport
      parentRoute: typeof PormtsRoute
    }
    '/pormts/saved': {
      id: '/pormts/saved'
      path: '/saved'
      fullPath: '/pormts/saved'
      preLoaderRoute: typeof PormtsSavedRouteImport
      parentRoute: typeof PormtsRoute
    }
    '/pormts/guide': {
      id: '/pormts/guide'
      path: '/guide'
      fullPath: '/pormts/guide'
      preLoaderRoute: typeof PormtsGuideRouteImport
      parentRoute: typeof PormtsRoute
    }
    '/pormts/collections': {
      id: '/pormts/collections'
      path: '/collections'
      fullPath: '/pormts/collections'
      preLoaderRoute: typeof PormtsCollectionsRouteImport
      parentRoute: typeof PormtsRoute
    }
    '/pormts/builder': {
      id: '/pormts/builder'
      path: '/builder'
      fullPath: '/pormts/builder'
      preLoaderRoute: typeof PormtsBuilderRouteImport
      parentRoute: typeof PormtsRoute
    }
    '/pormts/about': {
      id: '/pormts/about'
      path: '/about'
      fullPath: '/pormts/about'
      preLoaderRoute: typeof PormtsAboutRouteImport
      parentRoute: typeof PormtsRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/demos': {
      id: '/admin/demos'
      path: '/admin/demos'
      fullPath: '/admin/demos'
      preLoaderRoute: typeof AdminDemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pormts/prompt/$slug': {
      id: '/pormts/prompt/$slug'
      path: '/prompt/$slug'
      fullPath: '/pormts/prompt/$slug'
      preLoaderRoute: typeof PormtsPromptSlugRouteImport
      parentRoute: typeof PormtsRoute
    }
  }
}

interface PormtsRouteChildren {
  PormtsAboutRoute: typeof PormtsAboutRoute
  PormtsBuilderRoute: typeof PormtsBuilderRoute
  PormtsCollectionsRoute: typeof PormtsCollectionsRoute
  PormtsGuideRoute: typeof PormtsGuideRoute
  PormtsSavedRoute: typeof PormtsSavedRoute
  PormtsIndexRoute: typeof PormtsIndexRoute
  PormtsPromptSlugRoute: typeof PormtsPromptSlugRoute
}

const PormtsRouteChildren: PormtsRouteChildren = {
  PormtsAboutRoute: PormtsAboutRoute,
  PormtsBuilderRoute: PormtsBuilderRoute,
  PormtsCollectionsRoute: PormtsCollectionsRoute,
  PormtsGuideRoute: PormtsGuideRoute,
  PormtsSavedRoute: PormtsSavedRoute,
  PormtsIndexRoute: PormtsIndexRoute,
  PormtsPromptSlugRoute: PormtsPromptSlugRoute,
}

const PormtsRouteWithChildren =
  PormtsRoute._addFileChildren(PormtsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DemosRoute: DemosRoute,
  PormtsRoute: PormtsRouteWithChildren,
  PromptsRoute: PromptsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkRoute: WorkRoute,
  AdminDemosRoute: AdminDemosRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
